# Generated by Django 2.2.24 on 2022-02-17 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='historygold',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='search_gold',
        ),
        migrations.AlterField(
            model_name='austat',
            name='atype',
            field=models.CharField(default='def', max_length=5, verbose_name='Approval'),
        ),
        migrations.AlterField(
            model_name='austat',
            name='stype',
            field=models.CharField(choices=[('app', 'Approved'), ('edi', 'Edited'), ('imp', 'Imported'), ('man', 'Manually created'), ('-', 'Undefined')], default='-', max_length=5, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='austatlink',
            name='alternatives',
            field=models.CharField(blank=True, choices=[('no', 'No'), ('und', 'Undecided'), ('yes', 'Yes')], max_length=5, null=True, verbose_name='Alternatives'),
        ),
        migrations.AlterField(
            model_name='austatlink',
            name='linktype',
            field=models.CharField(choices=[('ech', 'echoes'), ('eqs', 'equals'), ('neq', 'nearly equals'), ('prt', 'partially equals'), ('sim', 'similar to'), ('uns', 'unspecified'), ('use', 'uses')], default='eqs', max_length=5, verbose_name='Link type'),
        ),
        migrations.AlterField(
            model_name='austatlink',
            name='spectype',
            field=models.CharField(blank=True, choices=[('com', 'Common source'), ('uns', 'Unspecified'), ('udd', 'Used by'), ('udi', 'Used by (indirect)'), ('usd', 'Uses'), ('usi', 'Uses (indirect)')], max_length=5, null=True, verbose_name='Specification'),
        ),
        migrations.AlterField(
            model_name='canwit',
            name='autype',
            field=models.CharField(choices=[('vun', '1 Very uncertain'), ('unc', '2 Uncertain'), ('ave', '3 Average'), ('rea', '4 Reasonably certain'), ('vce', '5 Very certain')], default='ave', max_length=5, verbose_name='Author certainty'),
        ),
        migrations.AlterField(
            model_name='canwit',
            name='mtype',
            field=models.CharField(choices=[('man', 'Manifestation'), ('rec', 'Reconstruction'), ('tem', 'Template')], default='man', max_length=5, verbose_name='Manifestation type'),
        ),
        migrations.AlterField(
            model_name='canwit',
            name='stype',
            field=models.CharField(choices=[('app', 'Approved'), ('edi', 'Edited'), ('imp', 'Imported'), ('man', 'Manually created'), ('-', 'Undefined')], default='man', max_length=5, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='canwitaustat',
            name='linktype',
            field=models.CharField(choices=[('ech', 'echoes'), ('eqs', 'equals'), ('neq', 'nearly equals'), ('prt', 'partially equals'), ('sim', 'similar to'), ('uns', 'unspecified'), ('use', 'uses')], default='uns', max_length=5, verbose_name='Link type'),
        ),
        migrations.AlterField(
            model_name='canwitsignature',
            name='editype',
            field=models.CharField(default='gr', max_length=5, verbose_name='Edition type'),
        ),
        migrations.AlterField(
            model_name='codico',
            name='stype',
            field=models.CharField(choices=[('app', 'Approved'), ('edi', 'Edited'), ('imp', 'Imported'), ('man', 'Manually created'), ('-', 'Undefined')], default='man', max_length=5, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='scope',
            field=models.CharField(choices=[('priv', 'Private'), ('publ', 'Public'), ('team', 'Team')], default='priv', max_length=5, verbose_name='Scope'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='settype',
            field=models.CharField(choices=[('hc', 'Historical Collection'), ('pd', 'Personal Dataset')], default='pd', max_length=5, verbose_name='Set type'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='type',
            field=models.CharField(choices=[('austa', 'Authoritative Statement'), ('canwi', 'Canon Witness'), ('colwi', 'Collection Witness'), ('manu', 'Manuscript')], max_length=5, verbose_name='Type of collection'),
        ),
        migrations.AlterField(
            model_name='colwit',
            name='stype',
            field=models.CharField(choices=[('app', 'Approved'), ('edi', 'Edited'), ('imp', 'Imported'), ('man', 'Manually created'), ('-', 'Undefined')], default='man', max_length=5, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='visibility',
            field=models.CharField(choices=[('all', 'All users'), ('edi', 'Editors only')], default='all', max_length=5, verbose_name='Visibility'),
        ),
        migrations.AlterField(
            model_name='library',
            name='libtype',
            field=models.CharField(choices=[('pl', 'plain')], max_length=5, verbose_name='Library type'),
        ),
        migrations.AlterField(
            model_name='library',
            name='stype',
            field=models.CharField(choices=[('app', 'Approved'), ('edi', 'Edited'), ('imp', 'Imported'), ('man', 'Manually created'), ('-', 'Undefined')], default='man', max_length=5, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='location',
            name='stype',
            field=models.CharField(choices=[('app', 'Approved'), ('edi', 'Edited'), ('imp', 'Imported'), ('man', 'Manually created'), ('-', 'Undefined')], default='man', max_length=5, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='mtype',
            field=models.CharField(choices=[('man', 'Manifestation'), ('rec', 'Reconstruction'), ('tem', 'Template')], default='man', max_length=5, verbose_name='Manifestation type'),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='stype',
            field=models.CharField(choices=[('app', 'Approved'), ('edi', 'Edited'), ('imp', 'Imported'), ('man', 'Manually created'), ('-', 'Undefined')], default='man', max_length=5, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='status',
            field=models.CharField(choices=[('ext', 'Extinct'), ('val', 'Valid')], help_text='Sorry, no help available for view.status', max_length=5, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ptype',
            field=models.CharField(choices=[('akw', 'Approved keyword editor'), ('dev', 'Developer of this application'), ('usr', 'Simple user'), ('unk', 'Unknown')], default='unk', max_length=5, verbose_name='Profile status'),
        ),
        migrations.AlterField(
            model_name='projecteditor',
            name='rights',
            field=models.CharField(choices=[('rdo', 'Read only'), ('edi', 'Reading and writing')], default='edi', max_length=5, verbose_name='Rights'),
        ),
        migrations.AlterField(
            model_name='projecteditor',
            name='status',
            field=models.CharField(choices=[('excl', 'Exclude'), ('incl', 'Include')], default='incl', max_length=5, verbose_name='Default assignment'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reptype',
            field=models.CharField(choices=[('ixlsx', 'Import Excel'), ('ijson', 'Import JSON')], max_length=5, verbose_name='Report type'),
        ),
        migrations.AlterField(
            model_name='userkeyword',
            name='type',
            field=models.CharField(choices=[('austa', 'Authoritative Statement'), ('canwi', 'Canon Witness'), ('colwi', 'Collection Witness'), ('manu', 'Manuscript')], max_length=5, verbose_name='Type of user keyword'),
        ),
    ]
