# Generated by Django 2.2.24 on 2022-02-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view', models.CharField(max_length=255, verbose_name='Listview')),
                ('params', models.TextField(default='[]', verbose_name='Parameters')),
                ('count', models.IntegerField(default=0, verbose_name='Count')),
                ('history', models.TextField(default='{}', verbose_name='History')),
            ],
            options={
                'verbose_name': 'User search',
                'verbose_name_plural': 'User searches',
            },
        ),
    ]
